apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes-api.fullname" . }}
  labels:
    {{- include "notes-api.labels" . | nindent 4 }}
  {{- if or .Values.service.loadBalancerIP .Values.service.resourceGroup }}
  annotations:
    {{- if .Values.service.resourceGroup }}
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.service.resourceGroup }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "notes-api.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
